server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
#              searchLocations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice,
#                               file://<chapter 3>confsvr/src/main/resources/config/organizationservice
              searchLocations: file:///D:/Projects/ComPro/SWA/spring-cloud-config/configserver/src/main/resources/config/
