spring:
  application:
    name: zuul-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    customers:
      serviceId: customers-service
    product:
      serviceId: product-service
    order:
      serviceId: order-service
    shopping:
      serviceId: shopping-service
