spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

server:
  port: 8092

logging:
  level:
    root: ERROR
#    org:
#      springframework.: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
