spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

server:
  port: 8092

logging:
  level:
    root: ERROR
#    org:
#      springframework.: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
