spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8094

logging:
  level:
    root: ERROR
#    org:
#      springframework.: ERROR

customersURL: http://localhost:8092
productsURL: http://localhost:8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
